const lessons=[
  {id:"fundamentos",kicker:"Fundamentos",title:"Diseñar para el cambio",summary:"Antes de dibujar clases hay que decidir por qué se divide el sistema y qué cambio intenta aislar cada parte.",theory:{title:"Idea central",text:"Diseñar es descomponer el software, asignar funciones y establecer relaciones. El criterio no es producir muchas partes: es reducir el costo de los cambios sin degradar la integridad conceptual.",concepts:[["Cambio probable","Anticipar qué requisito, algoritmo, dato o tecnología puede variar."],["Secreto del módulo","Cada módulo aísla una decisión de diseño con alta probabilidad de cambio."],["Interfaz estable","Los clientes usan servicios abstractos y no dependen de la implementación."]]},exercises:[
    {type:"choice",q:"Una empresa puede cambiar el proveedor de pagos varias veces. ¿Qué decisión sigue mejor a Parnas?",options:["Incluir condiciones del proveedor en Pedido","Aislar la integración tras una interfaz de pagos","Exponer el SDK del proveedor a todas las clases"],answer:1,why:"El proveedor es un ítem de cambio. Una interfaz estable evita propagar ese cambio."},
    {type:"choice",q:"¿Cuál es el objetivo principal de un buen diseño?",options:["Usar la mayor cantidad posible de clases","Minimizar el costo de cambio y preservar la integridad conceptual","Copiar directamente el modelo funcional"],answer:1,why:"La cantidad de clases no es el criterio; importa la descomposición frente al cambio."}
  ],source:"Apuntes Una Teoría para el Diseño de Software y Diseño de Software, secciones sobre Diseño para el Cambio y DBOI."},
  {id:"dominio",kicker:"ICONIX · Modelo de dominio",title:"Encontrar conceptos, no soluciones",summary:"El modelo de dominio establece el vocabulario conceptual antes de introducir detalles técnicos.",theory:{title:"Regla de trabajo",text:"Extraé conceptos del problema, sus atributos significativos y relaciones. No confundas entidades del dominio con pantallas, controladores o tablas de una tecnología particular.",concepts:[["Concepto","Objeto reconocible del mundo del problema."],["Atributo","Propiedad significativa del concepto."],["Relación","Vínculo semántico con cardinalidad."]]},exercises:[
    {type:"multi",q:"Seleccioná sólo conceptos del dominio de ventas.",options:["Cliente","PedidoVenta","Botón Confirmar","PostgreSQL","Producto"],answer:[0,1,4],why:"Cliente, PedidoVenta y Producto pertenecen al dominio; el botón y PostgreSQL son detalles de solución."},
    {type:"choice",q:"¿Cuál relación expresa mejor el dominio?",options:["PedidoVenta 1 contiene 1..* LíneaPedido","Form llama a SQL","Controlador importa ORM"],answer:0,why:"La primera relación usa conceptos y cardinalidad sin contaminar el modelo conceptual."}
  ],source:"Proceso ICONIX del repositorio: modelo de dominio conceptual y separación entre requerimientos y diseño."},
  {id:"casos",kicker:"ICONIX · Casos de uso",title:"Narrar comportamiento observable",summary:"Los casos de uso conectan objetivos de actores con respuestas del sistema y preparan el análisis de robustez.",theory:{title:"Del objetivo al flujo",text:"Nombrá el caso de uso con un verbo, identificá actor y objetivo, y redactá pasos en voz activa. Usá include para comportamiento obligatorio reutilizado y extend para comportamiento condicional.",concepts:[["Actor","Rol externo que persigue un objetivo."],["include","Subflujo obligatorio compartido."],["extend","Comportamiento opcional bajo condición."]]},exercises:[
    {type:"choice",q:"Enviar el presupuesto por email es opcional. ¿Qué relación corresponde?",options:["include","extend","generalización de actor"],answer:1,why:"El envío aparece sólo si el vendedor decide realizarlo."},
    {type:"sort",q:"Ordená el camino feliz de Crear presupuesto.",items:["El sistema calcula los totales","El vendedor selecciona el cliente","El vendedor guarda el presupuesto","El vendedor agrega productos"],answer:["El vendedor selecciona el cliente","El vendedor agrega productos","El sistema calcula los totales","El vendedor guarda el presupuesto"],why:"El orden conserva causa y efecto y luego podrá trazarse al diagrama de robustez."}
  ],source:"Casos de uso CU-VEN-001 y D-CU-GEN-002 del repositorio SAP-TFI-2026."},
  {id:"robustez",kicker:"ICONIX · Robustez",title:"Separar frontera, control y entidad",summary:"El análisis de robustez verifica que el texto del caso de uso pueda convertirse en colaboraciones de objetos.",theory:{title:"Tres responsabilidades",text:"El actor interactúa con fronteras; las fronteras invocan controles; los controles coordinan entidades. Evitá que la interfaz manipule directamente la persistencia o que una entidad asuma decisiones de presentación.",concepts:[["Boundary","Pantalla, formulario, API o mensaje visible."],["Control","Coordinador de un flujo o regla de aplicación."],["Entity","Concepto persistente con estado del dominio."]]},exercises:[
    {type:"classify",q:"Clasificá cada elemento del flujo Confirmar pedido.",items:[["Botón Confirmar","Boundary"],["action_confirm()","Control"],["sale.order","Entity"]],options:["Boundary","Control","Entity"],why:"La clasificación mantiene separadas interacción, coordinación y estado."},
    {type:"choice",q:"¿Qué interacción revela mayor acoplamiento indebido?",options:["Actor → Formulario","Formulario → Control","Formulario → PostgreSQL"],answer:2,why:"La frontera conoce un detalle de persistencia y saltea el control y las entidades."}
  ],source:"Diagramas D-ROB del repositorio y principio de bajo acoplamiento del apunte Diseño de Software."},
  {id:"secuencia",kicker:"ICONIX · Secuencia",title:"Asignar mensajes en el tiempo",summary:"El diagrama de secuencia refina el flujo de robustez y asigna operaciones concretas a participantes.",theory:{title:"Trazabilidad temporal",text:"Cada mensaje debe derivarse de un paso del caso de uso y de una interacción de robustez. Las alternativas se representan con condiciones explícitas y las operaciones se asignan al objeto que posee la responsabilidad.",concepts:[["Lifeline","Participante que existe durante la interacción."],["Mensaje","Solicitud de un servicio en orden temporal."],["alt / opt","Variación condicional del flujo."]]},exercises:[
    {type:"sort",q:"Ordená los mensajes de Confirmar pedido.",items:["Stock crea picking","Formulario invoca action_confirm()","Control valida pedido","sale.order cambia a sale"],answer:["Formulario invoca action_confirm()","Control valida pedido","sale.order cambia a sale","Stock crea picking"],why:"Primero se recibe la intención, luego se valida y sólo después se modifican entidades."},
    {type:"choice",q:"Si la validación puede fallar, ¿qué fragmento UML corresponde?",options:["loop","alt / else","par"],answer:1,why:"alt / else muestra caminos mutuamente excluyentes: éxito o error."}
  ],source:"Diagramas D-SEC del repositorio y trazabilidad definida por el proceso ICONIX."},
  {id:"clases",kicker:"ICONIX · Diagrama de clases",title:"Construir clases que oculten decisiones",summary:"El modelo de clases asigna datos, operaciones y relaciones sin exponer decisiones que probablemente cambien.",theory:{title:"De Parnas a UML",text:"Una clase no se justifica sólo porque exista un sustantivo: debe reunir una responsabilidad coherente y proteger un secreto. La interfaz pública debe ser pequeña, abstracta e insensible a cambios anticipados.",concepts:[["Alta cohesión","Los elementos internos contribuyen a un único secreto o responsabilidad."],["Bajo acoplamiento","Las clases conocen la menor cantidad necesaria de otras clases."],["Encapsulamiento","Los parámetros y retornos no revelan la representación interna."]]},exercises:[
    {type:"choice",q:"Un catálogo puede pasar de arreglo a base de datos. ¿Cuál interfaz oculta mejor esa decisión?",options:["Producto[] getArray()","Producto buscarPorId(IdProducto id)","Producto get(int posicion)"],answer:1,why:"Buscar por identidad expresa una necesidad del dominio sin exponer arreglo, posición ni capacidad."},
    {type:"builder",q:"Construí un diseño para descuentos variables.",tokens:["Pedido","PoliticaDescuento","BaseDatosDescuento","calcularTotal()","aplicarA(Pedido)","getFila(int)"],answer:["Pedido","PoliticaDescuento","calcularTotal()","aplicarA(Pedido)"],why:"Pedido compone una Política de Descuento mediante servicios del dominio; la tabla y el acceso por fila quedan ocultos."}
  ],source:"Diseño de Software, secciones DBOI, interfaz/implementación, abstracción, encapsulamiento, cohesión/acoplamiento y diseño orientado a objetos."},
  {id:"cuentas",kicker:"Taller · Ocultamiento",title:"Diseñar una cuenta con comisiones",summary:"Un problema nuevo para resolver en clase: separar la operación bancaria, la política de comisión y el historial de extracciones sin contaminar CajaAhorros.",theory:{title:"Objetivo del ejercicio",text:"Diseñar una extensión para cuentas bancarias aplicando Diseño Basado en Ocultamiento de la Información. La solución debe anticipar cambios, asignar un secreto coherente a cada módulo y mantener estable la interfaz que usan los clientes.",concepts:[["Desafío","Incorporar la regla sin modificar CajaAhorros."],["Restricción","Los clientes actuales deben conservar depositar, extraer y saldo."],["Entregable","Análisis de cambio, interfaces, relaciones y guía de módulos."]]},statement:"<p>El <b>Banco Horizonte</b> ofrece cajas de ahorro que permiten depositar dinero, extraerlo y consultar el saldo. El sistema ya cuenta con un módulo <code>CajaAhorros</code> probado y utilizado por otras aplicaciones.</p><pre>Module CajaAhorros\nimports Monto\nexports depositar(i Monto)\n        extraer(i Monto)\n        saldo(): Monto</pre><p>El banco incorpora un paquete de beneficios con una nueva regla: <b>las primeras tres extracciones exitosas de cada mes calendario son gratuitas; desde la cuarta, cada extracción tiene una comisión fija de $1.500</b>.</p><div class=\"statement-grid\"><section><h3>Reglas funcionales</h3><ol><li>Los depósitos no generan comisión ni alteran el contador de extracciones.</li><li>Cada caja de ahorro mantiene su propio historial mensual.</li><li>Una extracción alcanzada por la comisión debita del saldo el monto solicitado más $1.500.</li><li>Si el saldo no cubre el total, la operación se rechaza: no cambia el saldo ni se registra una extracción exitosa.</li><li>Al comenzar un nuevo mes, las extracciones exitosas vuelven a contarse desde cero.</li><li><code>saldo()</code> debe reflejar todos los débitos efectivamente realizados.</li></ol></section><section><h3>Cambios anticipados</h3><p>El área comercial advierte que podrían cambiar:</p><ul><li>la cantidad de extracciones gratuitas;</li><li>el valor o la forma de calcular la comisión;</li><li>la tecnología usada para guardar el historial.</li></ul><p>Estos cambios no deberían obligar a modificar ni reverificar la implementación ya probada de <code>CajaAhorros</code>.</p></section></div><div class=\"statement-deliverable\"><h3>Trabajo solicitado</h3><p>Proponer el diseño, no el código de una aplicación completa. La entrega debe incluir:</p><ol><li>análisis de los ítems de cambio y sus variaciones probables;</li><li>módulos propuestos y secreto ocultado por cada uno;</li><li>interfaces en notación 2MIL, con cláusulas <code>imports</code> y <code>exports</code>;</li><li>relaciones entre módulos y secuencia de una extracción;</li><li>guía de módulos con función y secreto;</li><li>validación del diseño frente a cambios futuros.</li></ol></div>",steps:[
    {title:"Leer el problema y marcar decisiones",body:"<p>Antes de proponer clases, subrayá qué pertenece a la operación bancaria estable y qué puede variar. <b>No abras todavía los pasos siguientes en clase:</b> pedí primero una hipótesis al grupo.</p><ul><li>Operación estable: depositar, extraer y consultar saldo.</li><li>Decisiones anticipadas: cantidad de extracciones gratuitas, cálculo de la comisión y almacenamiento del historial.</li></ul>"},
    {title:"Realizar el análisis de cambio",body:"<p>Detectamos dos ítems de cambio independientes:</p><ol><li><b>Política de comisión:</b> hoy son tres operaciones y $1.500; mañana puede variar por paquete, canal o monto.</li><li><b>Registro de extracciones:</b> hoy podría ser memoria; mañana archivo o base de datos.</li></ol><p>La gestión básica del saldo ya está aislada en <code>CajaAhorros</code> y no debe modificarse.</p>"},
    {title:"Descartar la solución monolítica",body:"<p>Agregar contador, fecha y comisión dentro de <code>CajaAhorros.extraer()</code> mezcla tres secretos: saldo, regla comercial y almacenamiento. Cada cambio obligaría a reverificar el módulo bancario completo y acumularía condicionales.</p><p><b>Pregunta para discutir:</b> si mañana desaparece la comisión, ¿qué código debería poder retirarse sin tocar la cuenta?</p>"},
    {title:"Asignar un secreto a cada módulo",body:"<ul><li><b>CajaAhorros:</b> oculta la representación del saldo y las operaciones básicas.</li><li><b>PoliticaComision:</b> oculta cómo se decide y calcula la comisión.</li><li><b>HistorialExtracciones:</b> oculta cómo se cuentan y almacenan las operaciones por período.</li><li><b>CuentaConComision:</b> coordina el caso, conserva la interfaz bancaria y delega.</li></ul>"},
    {title:"Diseñar interfaces abstractas",body:"<pre>Module CuentaConComision\nimports CajaAhorros, PoliticaComision, HistorialExtracciones, Monto\nexports depositar(i Monto)\n        extraer(i Monto)\n        saldo(): Monto\n\nModule PoliticaComision\nimports Monto, Cantidad\nexports calcular(i Cantidad, i Monto): Monto\n\nModule HistorialExtracciones\nimports CuentaId, Periodo\nexports cantidad(i CuentaId, i Periodo): Cantidad\n        registrar(i CuentaId, i Periodo)</pre><p>Las interfaces expresan servicios y no revelan si hay tablas, archivos, arreglos o constantes internas.</p>"},
    {title:"Establecer delegación y secuencia",body:"<ol><li>El cliente invoca <code>CuentaConComision.extraer(monto)</code>.</li><li>El coordinador consulta cuántas extracciones hubo en el período.</li><li>Pide a <code>PoliticaComision</code> calcular la comisión.</li><li>Delega en <code>CajaAhorros.extraer(monto + comisión)</code>.</li><li>Si la extracción tuvo éxito, registra la operación.</li></ol><p>Como <code>CuentaConComision</code> conserva la interfaz de la cuenta, el cliente no cambia. La operación debe informar éxito o error para no registrar intentos fallidos.</p>"},
    {title:"Validar el diseño con cambios",body:"<p>Un diseño se evalúa por el costo de los cambios probables:</p><div class=\"change-test\"><div><b>Cambiar a cinco extracciones gratis</b>Sólo cambia PoliticaComision.</div><div><b>Guardar el historial en SQL</b>Sólo cambia HistorialExtracciones.</div><div><b>Eliminar todas las comisiones</b>El cliente usa CajaAhorros directamente.</div><div><b>Agregar una comisión por transferencias</b>Se crea otra política o coordinador; no se altera el saldo.</div></div><p>Si una respuesta obliga a modificar varios módulos no relacionados, revisá el secreto o la interfaz.</p>"},
    {title:"Cerrar con la guía de módulos",body:"<p><b>CuentaConComision.</b> Función: coordinar una extracción aplicando comisión e historial. Secreto: la secuencia de colaboración de esta extensión.</p><p><b>PoliticaComision.</b> Función: calcular el cargo para una extracción. Secreto: parámetros y algoritmo comercial.</p><p><b>HistorialExtracciones.</b> Función: consultar y registrar extracciones por cuenta y período. Secreto: representación y tecnología de persistencia.</p><p><b>CajaAhorros.</b> Función: operaciones bancarias básicas. Secreto: representación y actualización del saldo.</p>"}
  ],exercises:[
    {type:"choice",q:"¿Cuál es el principal problema de guardar el contador mensual dentro de CajaAhorros?",options:["La clase tendrá pocas líneas","Mezcla el secreto del saldo con una política y su historial","Impide usar números enteros"],answer:1,why:"La representación del saldo y la regla de comisión cambian por razones diferentes; deben quedar aisladas."},
    {type:"multi",q:"Si cambia sólo la forma de persistir el historial, ¿qué módulos deberían requerir modificación?",options:["CajaAhorros","CuentaConComision","PoliticaComision","HistorialExtracciones"],answer:[3],why:"La interfaz estable permite reemplazar la persistencia sin propagar el cambio."}
  ],source:"Diseño de Software (Diseño para el Cambio, DBOI, metodología de Parnas e interfaz/implementación) y Problemas Resueltos – Diseño (problema de CajaAhorros y ControlExtraccion)."}
];

let lessonIndex=0;
let progress=JSON.parse(localStorage.getItem("iconix-progress")||"{}");
const selections={};

function saveProgress(){localStorage.setItem("iconix-progress",JSON.stringify(progress))}
function allCorrect(lesson){return lesson.exercises.every((_,i)=>progress[`${lesson.id}-${i}`])}
function renderNav(){
  document.querySelector("#lesson-list").innerHTML=lessons.map((lesson,i)=>`<button class="lesson-button ${i===lessonIndex?"active":""} ${allCorrect(lesson)?"done":""}" data-index="${i}"><span>${allCorrect(lesson)?"✓":i+1}</span><strong>${lesson.title}</strong><small>${lesson.kicker.replace("ICONIX · ","")}</small></button>`).join("");
  const completed=lessons.filter(allCorrect).length;
  document.querySelector("#progress-bar").style.width=`${completed/lessons.length*100}%`;
  document.querySelector("#progress-copy").textContent=`${completed} de ${lessons.length} estaciones completadas`;
}
function renderLesson(){
  const lesson=lessons[lessonIndex];
  document.querySelector("#lesson-kicker").textContent=lesson.kicker;document.querySelector("#lesson-title").textContent=lesson.title;document.querySelector("#lesson-summary").textContent=lesson.summary;
  const statement=lesson.statement?`<article class="case-brief"><p class="eyebrow">Enunciado completo</p><h2>Problema para resolver</h2>${lesson.statement}</article>`:"";
  const steps=lesson.steps?`<section aria-labelledby="step-title"><div class="step-heading"><p class="eyebrow">Resolución progresiva</p><h2 id="step-title">Abrí un paso por vez</h2><p>Cada acordeón revela una decisión de diseño y una pregunta para discutir.</p></div><div class="solution-steps">${lesson.steps.map((step,i)=>`<details class="solution-step"><summary><span class="step-number">${i+1}</span>${step.title}</summary><div class="step-body">${step.body}</div></details>`).join("")}</div></section>`:"";
  document.querySelector("#lesson-content").innerHTML=`<article class="theory-card"><p class="eyebrow">${lesson.theory.title}</p><p>${lesson.theory.text}</p></article><div class="concept-grid">${lesson.theory.concepts.map(c=>`<article class="concept-card"><b>${c[0]}</b><p>${c[1]}</p></article>`).join("")}</div>${statement}${steps}${lesson.exercises.map((e,i)=>exerciseHTML(e,i,lesson.id)).join("")}<p class="source-note"><b>Base conceptual:</b> ${lesson.source} Fuentes: <a href="https://www.fceia.unr.edu.ar/ingsoft/intro-diseno.pdf" target="_blank" rel="noreferrer">Introducción al diseño ↗</a> · <a href="https://www.fceia.unr.edu.ar/ingsoft/diseno-a.pdf" target="_blank" rel="noreferrer">Diseño y ocultamiento de información ↗</a></p>`;
  document.querySelector("#previous-lesson").disabled=lessonIndex===0;document.querySelector("#next-lesson").textContent=lessonIndex===lessons.length-1?"Finalizar ✓":"Siguiente →";
  updateScore();renderNav();
}
function exerciseHTML(e,i,id){
  const common=`<header><div><h3>${i+1}. ${e.q}</h3></div><span class="exercise-type">${({choice:"Una respuesta",multi:"Selección múltiple",sort:"Ordenar",classify:"Clasificar",builder:"Construir"})[e.type]}</span></header>`;
  let body="";
  if(e.type==="choice"||e.type==="multi")body=`<div class="options">${e.options.map((o,n)=>`<button class="option" data-option="${n}"><span>${e.type==="multi"?"□":"○"}</span>${o}</button>`).join("")}</div>`;
  if(e.type==="sort")body=`<div class="sort-list">${e.items.map((item,n)=>`<div class="sort-item" data-value="${item}"><i>${n+1}</i><span>${item}</span><div class="sort-controls"><button data-move="up">↑</button><button data-move="down">↓</button></div></div>`).join("")}</div>`;
  if(e.type==="classify")body=`<div class="options">${e.items.map((item,n)=>`<label class="option">${item[0]}<select data-classify="${n}"><option value="">Elegir…</option>${e.options.map(o=>`<option>${o}</option>`).join("")}</select></label>`).join("")}</div>`;
  if(e.type==="builder")body=`<div class="builder"><div class="palette"><h4>Elementos disponibles</h4>${e.tokens.map((t,n)=>`<button class="token" data-token="${n}">${t}</button>`).join("")}</div><div class="canvas"><h4>Tu diagrama</h4><div class="uml-preview" data-preview><p>Elegí clases y operaciones.</p></div></div></div>`;
  return `<article class="exercise-card" data-exercise="${i}" data-type="${e.type}" data-lesson="${id}">${common}${body}<button class="check-button" data-check>Comprobar</button><div class="feedback"></div></article>`
}
function updateScore(){const lesson=lessons[lessonIndex];const score=lesson.exercises.filter((_,i)=>progress[`${lesson.id}-${i}`]).length;document.querySelector("#lesson-score").textContent=`${score} / ${lesson.exercises.length}`}
function checkExercise(card){
  const lesson=lessons[lessonIndex],i=Number(card.dataset.exercise),e=lesson.exercises[i];let correct=false;
  if(e.type==="choice")correct=Number(card.querySelector(".option.selected")?.dataset.option)===e.answer;
  if(e.type==="multi"){const got=[...card.querySelectorAll(".option.selected")].map(x=>Number(x.dataset.option)).sort();correct=JSON.stringify(got)===JSON.stringify(e.answer)}
  if(e.type==="sort")correct=JSON.stringify([...card.querySelectorAll(".sort-item")].map(x=>x.dataset.value))===JSON.stringify(e.answer);
  if(e.type==="classify")correct=[...card.querySelectorAll("select")].every((x,n)=>x.value===e.items[n][1]);
  if(e.type==="builder"){const got=selections[`${lesson.id}-${i}`]||[];correct=e.answer.every(x=>got.includes(x))&&got.every(x=>e.answer.includes(x))}
  const feedback=card.querySelector(".feedback");feedback.className=`feedback visible ${correct?"success":"error"}`;feedback.textContent=`${correct?"✓ Correcto.":"Todavía no."} ${e.why}`;
  progress[`${lesson.id}-${i}`]=correct;saveProgress();updateScore();renderNav();
}
document.querySelector("#lesson-content").addEventListener("click",event=>{
  const card=event.target.closest(".exercise-card");if(!card)return;
  if(event.target.closest("[data-option]")){const option=event.target.closest("[data-option]");if(card.dataset.type==="choice")card.querySelectorAll(".option").forEach(o=>o.classList.remove("selected"));option.classList.toggle("selected")}
  const mover=event.target.closest("[data-move]");if(mover){const row=mover.closest(".sort-item"),sibling=mover.dataset.move==="up"?row.previousElementSibling:row.nextElementSibling;if(sibling)row.parentElement.insertBefore(mover.dataset.move==="up"?row:sibling,mover.dataset.move==="up"?sibling:row)}
  const token=event.target.closest("[data-token]");if(token){const key=`${lessons[lessonIndex].id}-${card.dataset.exercise}`,value=lessons[lessonIndex].exercises[card.dataset.exercise].tokens[token.dataset.token];selections[key]=selections[key]||[];selections[key]=selections[key].includes(value)?selections[key].filter(x=>x!==value):[...selections[key],value];token.classList.toggle("active");card.querySelector("[data-preview]").innerHTML=builderPreview(selections[key])}
  if(event.target.closest("[data-check]"))checkExercise(card);
});
function builderPreview(items){const classes=items.filter(x=>!x.includes("(")&&!x.startsWith("Base"));const ops=items.filter(x=>x.includes("("));if(!items.length)return"<p>Elegí clases y operaciones.</p>";return classes.map((c,i)=>`<div class="uml-box"><strong>${c}</strong><div>${ops[i]||"+ interfaz abstracta"}</div></div>`).join('<div class="relationship">◇── usa ──▷</div>')}
document.querySelector("#lesson-list").addEventListener("click",e=>{const b=e.target.closest("[data-index]");if(b){lessonIndex=Number(b.dataset.index);renderLesson()}});
document.querySelector("#previous-lesson").addEventListener("click",()=>{if(lessonIndex>0){lessonIndex--;renderLesson();scrollTo(0,0)}});
document.querySelector("#next-lesson").addEventListener("click",()=>{if(lessonIndex<lessons.length-1){lessonIndex++;renderLesson();scrollTo(0,0)}else document.querySelector("#completion-dialog").showModal()});
document.querySelector("#reset-progress").addEventListener("click",()=>{progress={};saveProgress();renderLesson()});document.querySelector("#close-dialog").addEventListener("click",()=>document.querySelector("#completion-dialog").close());
renderLesson();
